## plt and plotr: SciVis-2023 Project 1
## Copyright (C)  2023 University of Chicago. All rights reserved.

# This little stub Makefile is here just to simplify debugging and
# development while in this "grade" subdirectory. With this, typing
# "make" here inside "grade" is the same as typing "make grade/plotr"
# in the parent directory above.

.PHONY:plotr # forces a "build" every time
plotr:
	(cd ..; make grade/plotr)
