/*
  plt and plotr: SciVis-2023 Project 1
  Copyright (C)  2023 University of Chicago. All rights reserved.

  This is only for students and instructors in the 2023 CMSC 23710/33710
  ("SciVis") class, for use in that class. It is not licensed for open-source
  or any other kind of re-distribution. Do not allow this file to be copied
  or downloaded by anyone outside the 2023 SciVis class.
*/

#include "plt.h"
#include "pltPrivate.h"

#define LIB      "plt"
#define LLIIBB   "PLT"
#define CMD      "plotr"
#define PNM      "1"
#define INFO     "Info about plotr and what to do for Project " PNM
#define BUFFSIZE 512

extern const char *pltTodo[]; // in plotr_todo.c

static int
aboutMain(int argc, const char **argv, const char *me, hestParm *hparm) {
    USED(argc);
    USEd(argv, me);
    static const char par1[] = "\t"
                               "\"" CMD "\" is a command-line tool wrapped around "
                               "functions in the \"" LIB
                               "\" library, which contains the code "
                               "that you (the student) must finish for Project " PNM
                               ".\n ";
    static const char par2[] = "\t"
                               "Like svn and git, " CMD
                               " has multiple subcommands, which you "
                               "indicate with the first argument to " CMD ", e.g. \"" CMD
                               " klist\". "
                               "A list and short description of all available " CMD
                               " commands is generated by typing just \"" CMD "\". \n";
    static const char par3[] = "\t"
                               "Detailed information and command-line option "
                               "documentation for \"" CMD
                               " foo\" (for example) is generated by "
                               "running \"" CMD " foo --help\". \n";
    static const char par4[]
      = "\t"
        "Your work on the project should start by reading " LIB ".h, to "
        "understand the structs, functions, and files involved. Also, skim "
        "the Makefile to get a sense of how things are compiled, and why it "
        "is important to limit your edits to the indicated regions for "
        "student work. Here is a list (also generated by \"plotr todo\") of "
        "the functions you need to finish, the " CMD " commands that test "
        "them (which you should use to debug your code), and the tests that "
        "cover them:\n ";
    static const char par5[]
      = "\t"
        "Note that the list above is a good order in which to do the work; "
        "later functions tend to rely on earlier functions. "
        "The correctness part of your grade will depend on the output "
        "that the above \"" CMD "\" commands generate.  That is, grading "
        "will involve a scripted execution of various " CMD " commands.\n ";
    static const char par6[]
      = "\t"
        "If you want to add debugging pltPrintf() statements, wrap them with,"
        " e.g., \"if (" LIB "Verbose) \" or \"if (" LIB "Verbose > 1)\". If " LIB
        "Verbose is 0, your code should not produce any debugging "
        "messages (at least nothing beyond what the reference implementation "
        "prints). You control the value of " LIB "Verbose at run-time by "
        "setting the environment variable SCIVIS_VERBOSE, e.g., \"export "
        "SCIVIS_VERBOSE=2\". \"" CMD "\" starts by using getenv() to learn "
        "the value of SCIVIS_VERBOSE (if any) then sets " LIB "Verbose "
        "accordingly. On the other hand, compiling with \"make clean; "
        "make CFLAGS=-DNDEBUG\" (as is done for grading) will "
        "#define " LIB "Verbose as 0, to wholly avoid both the debugging "
        "messages, and the performance cost of even checking " LIB "Verbose. ";
    static const char par7[]
      = "\t"
        "The floating-point rounding mode can be controlled by setting "
        "environment variable SCIVIS_ROUND to one of the strings "
        "\"NEAREST\", \"UPWARD\", \"DOWNWARD\", or \"BRACKET\". ";

    fprintf(stderr, "\n");
    char buff[BUFFSIZE], fmt[BUFFSIZE];
    const char banner[] = "--- %s: SciVis-2023 Project %s"
#ifdef SCIVIS_GRADE
                          " (For Grading)"
#endif
                          " ---";
    sprintf(buff, banner, CMD, PNM);
    sprintf(fmt, "%%%ds\n",
            (int)((hparm->columns - strlen(buff)) / 2 + strlen(buff) - 1));
    fprintf(stderr, fmt, buff);
    fprintf(stderr, "\n");

    _hestPrintStr(stderr, 1, 0, hparm->columns, par1, AIR_FALSE);
    _hestPrintStr(stderr, 1, 0, hparm->columns, par2, AIR_FALSE);
    _hestPrintStr(stderr, 1, 0, hparm->columns, par3, AIR_FALSE);
    _hestPrintStr(stderr, 1, 0, hparm->columns, par4, AIR_FALSE);
    char *todo = pltTodoStr(pltTodo);
    fprintf(stderr, "%s\n", todo);
    airFree(todo);
    _hestPrintStr(stderr, 1, 0, hparm->columns, par5, AIR_FALSE);
    _hestPrintStr(stderr, 1, 0, hparm->columns, par6, AIR_FALSE);
    fprintf(stderr, " Currently, " LIB "Verbose == %d\n", pltVerbose);
#ifdef NDEBUG
    fprintf(stderr, " This WAS IN FACT compiled with "
                    "\"make CFLAGS=-DNDEBUG\"\n");
#else
    fprintf(stderr, " (This was compiled without \"make CFLAGS=-DNDEBUG\")\n");
#endif
    _hestPrintStr(stderr, 1, 0, hparm->columns, par7, AIR_FALSE);
    {
        const char rstr[] = "SCIVIS_ROUND";
        const char *rval = getenv(rstr);
        if (rval) {
            fprintf(stderr, " (currently envvar \"%s\" set to \"%s\")\n", rstr, rval);
        } else {
            fprintf(stderr, " (currently envvar \"%s\" not set)\n", rstr);
        }
    }

    if (pltRealIsDouble) {
        fprintf(stderr, " (This was compiled with: "
                        "make CFLAGS=-DSCIVIS_REAL_IS_DOUBLE=1 so real == double)\n");
    } else {
        fprintf(stderr, " (This was compiled so real == float)\n");
    }

    return 0;
}

unrrduCmd plt_aboutCmd = {"about", INFO, aboutMain, AIR_FALSE};
