/*
  plt and plotr: SciVis-2023 Project 1
  Copyright (C)  2023 University of Chicago. All rights reserved.

  This is only for students and instructors in the 2023 CMSC 23710/33710
  ("SciVis") class, for use in that class. It is not licensed for open-source
  or any other kind of re-distribution. Do not allow this file to be copied
  or downloaded by anyone outside the 2023 SciVis class.
*/

#include "plt.h"
#include "pltPrivate.h"
#ifdef SCIVIS_GRADE
#  include "rplt.h"
#  include "pltGrade.h"
#endif

#define INFO "Convert from index-space to world-space"
static char *infoLong = (INFO ". The main work is done with pltItoW(); use this command "
                              "to debug your implementation.");

static int
itowMain(int argc, const char **argv, const char *me, hestParm *hparm) {
    airArray *mop = airMopNew();
    hestOpt *hopt = NULL;
    char *fname;
    hestOptAdd(&hopt, NULL, "data", airTypeString, 1, 1, &fname, NULL,
               "filename of data (e.g. generated by \"plotr psamp\")");
    real ipos;
    hestOptAdd(&hopt, NULL, "pos", airTypeReal, 1, 1, &ipos, NULL,
               "position in index-space of data, to convert to world-space");
    hestParseOrDie(hopt, argc, argv, hparm, me, infoLong, AIR_TRUE, AIR_TRUE, AIR_TRUE);
    airMopAdd(mop, hopt, (airMopper)hestOptFree, airMopAlways);
    airMopAdd(mop, hopt, (airMopper)hestParseFree, airMopAlways);

    // . . . . . . . . . . . . . . . . . useful code here
    pltData *data = pltDataNew();
    airMopAdd(mop, data, (airMopper)pltDataNix, airMopAlways);
    if (pltDataLoad(data, fname)) {
        ERROR(PLT, "trouble with data");
    }
    pltRoundSet();
    real wpos = pltItoW(data, ipos);
    pltRoundUnset();
    // ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' useful code here
#ifndef SCIVIS_GRADE
    pltPrintf("%g = pltItoW(%s, %g)\n", wpos, fname, ipos);
#else
    pltRoundSet();
    real rwpos = ref_pltItoW(data, ipos);
    pltRoundUnset();
    pltPrintf("%s: trying pltItoW(%s, %g)\n", me, fname, ipos);
    pltPrintf("%s: you: %g\n", me, wpos);
    pltPrintf("%s: ref: %g\n", me, rwpos);
    pltGradeReal(wpos, rwpos, "world-space position");
#endif

    airMopOkay(mop);
    return 0;
}

unrrduCmd plt_itowCmd = {"itow", INFO, itowMain, AIR_FALSE};
